### ISSUE TITLE
Calling `MultiplexServer.close()` causes an error

### ISSUE THREAD

**Issue by trentmwillis** [johnspackman/chrome-remote-multiplex#1]
First off, thanks a bunch for this library! It's working great for my use case 💯 

That said, I've run into a bug. Given:

```js
const server = new MultiplexServer();
await server.listen();
server.close();
```

You get the following error:

```bash
Cannot read property 'close' of undefined
```

It looks like this is because `this.express` is never assigned a value, so when `this.express.close()` gets called [here](https://github.com/johnspackman/chrome-remote-multiplex/blob/dc5438be44b1d6a7c9cf2a6641aae29defcbe00d/src/multiplex.js#L753), things go wrong. I plan to submit a PR to fix, but don't know when I'll get to it, so I'm opening this issue in case you can get to it before me.

**Comment by johnspackman** [comment]
Hi Trent

Thanks for the report - I've just fixed it and published a new version, please can you try again?

**Comment by trentmwillis** [comment]
Seems to be working correctly now, thanks a bunch!
